baseURL = "https://kevinkien.github.io/"
languageCode = "en-us"
title = "Kevin Kien Site"
theme = 'archie'

[params]
mode = "dark" # color-mode → light,dark or auto
useCDN = true
favicon = "https://github.com/athul.png"
og_image = "https://file.coffee/u/zrbyj5l-Ek.png"
sitename = "Kevin Kien Blog"
description = "Kevin Kien Personal Website built with Hugo and Archie Theme"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3


####
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/kevinkien"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/"